<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>.s</string>
		<string>.asm</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>name</key>
	<string>6809 Assembler</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
<string>\b(abx|adca|adcb|adda|addb|addd|anda|andb|andcc|asla|aslb|asl|asra|asrb|asr|bita|bitb|clra|clrb|clr|cmpa|cmpb|cmpd|cmps|cmpu|cmpx|cmpy|coma|comb|com|cwai|daa|deca|decb|dec|eora|eorb|exg|inca|incb|inc|jmp|jsr|lda|ldb|ldd|lds|ldu|ldx|ldy|leas|leau|leax|leay|lsl|lsra|mul|nega|negb|neg|nop|ora|orb|orcc|pshs|pshu|puls|pulu|rola|rolb|rol|rora|rorb|ror|sbca|sbcb|sex|sta|stb|std|stu|stx|sty|suba|subb|subd|tfr)\b</string>
			<!-- These are 6502 instructions: <string>\b(adc|and|asl|bit|clc|cld|cli|clv|cmp|cpx|cpy|dec|dex|dey|eor|inc|inx|iny|lda|ldx|ldy|lsr|nop|ora|pha|php|pla|plp|rol|ror|sbc|sec|sed|sei|sta|stx|sty|tax|txa|tay|tya|tsx|txs)\b</string> -->
			<key>name</key>
			<string>keyword</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(bcc|bcs|beq|bge|bgt|bhi|bhs|ble|blo|bls|blt|bmi|bne|bpl|bra|brn|bsr|bvc|bvs|rti|rts|swi|swi2|swi3|sync|tsta|tstb|tst|IF|ELSE|ELSIF|ENDIF)\b</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(;).*$\n?</string>
			<key>name</key>
			<string>comment.line.semicolon</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(SET|WORD|BYTE|HEX|DB|BYTE|DC.B|DW|WORD|DC.W|DL|LONG|DC.L|DRW|DS|RMB|BLKB|FCC|SEG|RSEG|SEG.U|WORDSIZE)\b</string>
			<key>name</key>
			<string>storage.type</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(ALIGN|EVEN|SETDP|WARNDP)\b</string>
			<key>name</key>
			<string>storage.modifier</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(ERROR|SUBROUTINE|SUBR|INCBIN|INCLUDE|LIST|OPT|MACRO|ENDM)\b</string>
			<key>name</key>
			<string>support.function</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(CPU|PROCESSOR|ORG)\b</string>
			<key>name</key>
			<string>constant.language</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.untitled</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.untitled</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>^[A-Za-z_][A-Za-z0-9_]*</string>
			<key>name</key>
			<string>entity.name.label</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\.[A-Za-z_][A-Za-z0-9_]*</string>
			<key>name</key>
			<string>entity.name.label.local</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#?\$[0-9a-fA-F]+</string>
			<key>name</key>
			<string>constant.numeric.hex</string>
		</dict>
		<dict>
			<key>match</key>
			<string>{[0-9]+}</string>
			<key>name</key>
			<string>variable.parameter.macro</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.assembly.6809.asmx</string>
	<key>uuid</key>
	<string>8D1E7063-570E-4E88-AF2E-EA3CE330B2D3</string>
</dict>
</plist>
